# Development tools and environment
{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:
{
  # Use GNU Emacs with Spacemacs configuration
  programs.emacs = {
    enable = true;
    # Use emacs-overlay's Emacs for consistent, up-to-date packages
    package = pkgs.emacs-unstable;
    # Pre-install core packages Spacemacs expects to avoid ELPA bootstrap issues
    extraPackages =
      epkgs:
      let
        claudeCode = epkgs.trivialBuild {
          pname = "claude-code";
          version = "unstable-2025-10-10";
          src = pkgs.fetchFromGitHub {
            owner = "stevemolitor";
            repo = "claude-code.el";
            rev = "becece683bcf60f7b150a87a30ef14885dcf8ce3";
            hash = "sha256-AW3Q5XScvT3UAmzvoMS53iZtijrii6pwvQjw+VW353w=";
          };
          packageRequires = with epkgs; [
            vterm
            inheritenv
            transient
          ];
        };
        aiCodeInterface = epkgs.trivialBuild {
          pname = "ai-code-interface";
          version = "0.60.0";
          src = pkgs.fetchFromGitHub {
            owner = "tninja";
            repo = "ai-code-interface.el";
            rev = "ec8c8ca8b839bcaa3bb93a1b79cf27ba86372094";
            hash = "sha256-zgKmy3QARY1J8B1Y72vs4seO2SsH3dsxabDp6AaSQyk=";
          };
          packageRequires =
            (with epkgs; [
              org
              magit
              transient
              seq
            ])
            ++ [ claudeCode ];
        };
      in
      (with epkgs; [
        use-package
        evil
        general
        which-key
        ivy
        counsel
        swiper
        company
        yasnippet
        flycheck
        projectile
        magit
        forge
        treemacs
        treemacs-evil
        treemacs-projectile
        gruvbox-theme
        # Nix syntax highlighting
        nix-mode
        # Email: ensure mu4e and notifications are available to Emacs
        mu4e
        mu4e-alert
        vterm
      ])
      ++ [
        claudeCode
        aiCodeInterface
      ];
  };

  # Spacemacs user configuration: set Gruvbox Dark Hard theme
  home.file.".spacemacs".text = ''
    ;; Minimal Spacemacs configuration generated by Home Manager
    ;; Focus on using the gruvbox-dark-hard theme

    (defun dotspacemacs/layers ()
      (setq-default
       dotspacemacs-distribution 'spacemacs
       dotspacemacs-enable-lazy-installation 'unused
       dotspacemacs-ask-for-lazy-installation t
       dotspacemacs-install-packages 'used-only
       dotspacemacs-configuration-layers '(
         ;; Core UX layers (adjust over time)
         better-defaults
         git
         (auto-completion :variables auto-completion-enable-snippets-in-popup t)
         syntax-checking
         treemacs
         ;; Choose one completion framework (ivy/helm/vertico). Default to ivy.
         ivy
         ;; Language layers for day-to-day development
         c-c++
         cmake
         python
         rust
         shell-scripts
         ;; Email (mu4e)
         (mu4e :variables
               mu4e-enable-notifications t
               mu4e-enable-mode-line t
               mu4e-use-maildirs-extension t)
       )
        dotspacemacs-additional-packages '(gruvbox-theme ai-code-interface vterm gptel mcp gptel-autocomplete)
        dotspacemacs-excluded-packages '(forge)))

    (defun dotspacemacs/init ()
      (setq-default
       dotspacemacs-editing-style 'vim
       dotspacemacs-elpa-https t
       dotspacemacs-verify-spacelpa-archives nil
       dotspacemacs-themes '(gruvbox-dark-hard)
       dotspacemacs-colorize-cursor-according-to-state t
       dotspacemacs-mode-line-theme 'spacemacs
       dotspacemacs-scratch-mode 'text-mode
       dotspacemacs-startup-banner 'official
       dotspacemacs-startup-lists '((recents . 5) (projects . 7))))

    (defun dotspacemacs/user-init ()
      ;; Quieten native-comp warnings during async compilation
      (when (boundp 'native-comp-async-report-warnings-errors)
        (setq native-comp-async-report-warnings-errors 'silent)))

      (defun dotspacemacs/user-config ()
        ;; Ensure Nix-provided Forge is loaded (without ELPA install)
        (with-eval-after-load 'magit
          (require 'forge))

        ;; mu4e basic wiring for Home Manager accounts
        (with-eval-after-load 'mu4e
        ;; maildir base from Home Manager accounts
        (setq mu4e-maildir (expand-file-name "mail" (getenv "HOME")))
        ;; Use mbsync for getting mail
        (setq mu4e-get-mail-command "mbsync -a")
        ;; Avoid indexing too often in-Emacs; rely on systemd timer, but keep manual update
        (setq mu4e-index-cleanup nil
              mu4e-index-lazy-check t)

        ;; Notifications via mu4e-alert (libnotify → mako)
        (require 'mu4e-alert)
        (mu4e-alert-set-default-style 'libnotify)
        ;; Only notify for unread, non-trashed mail in INBOX of the primary account
        ;; Adjust maildir if your account name differs
        (setq mu4e-alert-interesting-mail-query
              "flag:unread and not flag:trashed and maildir:/ludovic/INBOX")
        (mu4e-alert-enable-mode-line-display)
        (mu4e-alert-enable-notifications))

      ;; Ensure all interactive shells (SPC ') use fish with our system config
      (let ((fish "/run/current-system/sw/bin/fish"))
        (setq shell-file-name fish
              explicit-shell-file-name fish
              vterm-shell fish)
        (setenv "SHELL" fish)
        (with-eval-after-load 'shell-pop
          (setq shell-pop-shell-type `("ansi-term" "*shell*" (lambda () (ansi-term ,fish)))))
        (setq multi-term-program fish))

      ;; Language-specific tweaks without full Spacemacs layers
      (use-package nix-mode
        :mode "\\.nix\\'"
        :config
        (setq nix-indent-function 'nix-indent-line))

      (use-package claude-code
        :init
        (setq claude-code-terminal-backend 'vterm
              claude-code-program "codex"
              claude-code-program-switches nil))

      (use-package ai-code-interface
        :commands (ai-code-menu ai-code-cli-start ai-code-cli-resume ai-code-cli-switch-to-buffer ai-code-send-command)
        :init
        (setq ai-code-cli "codex")
        :config
        (ai-code-set-backend 'codex)
        (global-set-key (kbd "C-c a") #'ai-code-menu)
        (with-eval-after-load 'magit
          (ai-code-magit-setup-transients)))

      (require 'core-keybindings)
      (spacemacs/declare-prefix "oc" "AI Code")
      (spacemacs/set-leader-keys
        "oca" #'ai-code-menu
        "ocs" #'ai-code-cli-start
        "ocr" #'ai-code-cli-resume
        "ocb" #'ai-code-cli-switch-to-buffer
        "occ" #'ai-code-code-change
        "ocp" #'ai-code-send-command
        "oc|" #'ai-code-apply-prompt-on-current-file)

      ;; Ensure GNU Make files detect correctly (Makefile, .mk, etc.)
        (add-to-list 'auto-mode-alist '("\\.mk\\'" . makefile-gmake-mode))
        (add-to-list 'auto-mode-alist '("Makefile\\." . makefile-gmake-mode))

        ;; Per-mode line numbers
        (defun my/prog-mode-line-numbers ()
          "Enable absolute line numbers in programming buffers."
          (setq display-line-numbers-type 'absolute)
          (display-line-numbers-mode 1))

        (add-hook 'prog-mode-hook #'my/prog-mode-line-numbers)

        ;; Keep Treemacs visible when opening project files.
        (with-eval-after-load 'treemacs
          (treemacs-define-RET-action 'file-node-closed #'treemacs-visit-node-ace)
          (treemacs-define-RET-action 'file-node-open #'treemacs-visit-node-ace))

      ;; --- AI CLI helpers via gptel + MCP (keyless, CLI-driven) -----------
      ;; We do NOT configure any remote API backends; we drive local CLIs.
      ;; Packages are in dotspacemacs-additional-packages for MELPA install.

      (use-package gptel
        :commands (gptel gptel-send gptel-menu)
        :init (setq gptel-default-mode 'org-mode))

      (use-package mcp
        :after gptel
        :commands (mcp-hub mcp-hub-start-server mcp-connect-server mcp-call-tool)
        :init (require 'mcp-hub)
        :config
        ;; Start Codex MCP on demand; Claude Code optional via npx.
        (setq mcp-hub-servers
              '(("codex" . (:command "codex" :args ("mcp-server"))))))

      (use-package gptel-autocomplete
        :after gptel
        :commands (gptel-complete gptel-accept-completion)
        :init
        (define-minor-mode ai-code-ac-accept-tab-mode
          "Accept gptel-autocomplete with TAB when visible."
          :init-value t :lighter " AC-TAB"
          (if ai-code-ac-accept-tab-mode
              (local-set-key (kbd "TAB") #'gptel-accept-completion)
            (local-unset-key (kbd "TAB"))))
        (dolist (hook '(prog-mode-hook text-mode-hook))
          (add-hook hook (lambda () (ai-code-ac-accept-tab-mode 1)))))

      ;; --------------------------------------------------------------------
      )
  '';

  # Provide Spacemacs from flake input (tracked in flake.lock)
  home.file.".emacs.d" = {
    source = inputs.spacemacs;
    recursive = true;
  };

  # Remove old XDG init to ensure Spacemacs loads (Emacs 27+ prefers XDG)
  home.activation.removeXDGInit = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    XDG_INIT="${config.home.homeDirectory}/.config/emacs/init.el"
    if [ -L "$XDG_INIT" ] || [ -f "$XDG_INIT" ]; then
      echo "[home.activation] Removing legacy XDG init at $XDG_INIT" >&2
      rm -f "$XDG_INIT"
      rmdir --ignore-fail-on-non-empty "${config.home.homeDirectory}/.config/emacs" 2>/dev/null || true
    fi
  '';

  programs.nh = {
    enable = true;
    clean.enable = true;
    clean.extraArgs = "--keep-since 4d --keep 3";
    flake = "${config.home.homeDirectory}/Code/personal/dotfiles";
  };

  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
  };

  programs.java = {
    enable = true;
    package = pkgs.openjdk21;
  };
}
