# Development tools and environment
{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:
{
  # Use GNU Emacs with Spacemacs configuration
  programs.emacs = {
    enable = true;
    # Use emacs-overlay's Emacs for consistent, up-to-date packages
    package = pkgs.emacs-unstable;
    # Pre-install core packages Spacemacs expects to avoid ELPA bootstrap issues
    extraPackages = epkgs: [
      epkgs.use-package
      epkgs.evil
      epkgs.general
      epkgs.which-key
      epkgs.ivy
      epkgs.counsel
      epkgs.swiper
      epkgs.company
      epkgs.yasnippet
      epkgs.flycheck
      epkgs.projectile
      epkgs.magit
      epkgs.forge
      epkgs.treemacs
      epkgs.treemacs-evil
      epkgs.treemacs-projectile
      epkgs.gruvbox-theme
      # Nix syntax highlighting
      epkgs.nix-mode
    ];
  };

  # Spacemacs user configuration: set Gruvbox Dark Hard theme
  home.file.".spacemacs".text = ''
    ;; Minimal Spacemacs configuration generated by Home Manager
    ;; Focus on using the gruvbox-dark-hard theme

    (defun dotspacemacs/layers ()
      (setq-default
       dotspacemacs-distribution 'spacemacs
       dotspacemacs-enable-lazy-installation 'unused
       dotspacemacs-ask-for-lazy-installation t
       dotspacemacs-configuration-layers '(
         ;; Core UX layers (adjust over time)
         better-defaults
         git
         (auto-completion :variables auto-completion-enable-snippets-in-popup t)
         syntax-checking
         treemacs
         ;; Choose one completion framework (ivy/helm/vertico). Default to ivy.
        ivy
        ;; Nix language support (nix-mode)
        nix
        ;; Email (mu4e)
        mu4e
       )
        dotspacemacs-additional-packages '(gruvbox-theme)
        dotspacemacs-excluded-packages '(forge)))

    (defun dotspacemacs/init ()
      (setq-default
       dotspacemacs-editing-style 'vim
       dotspacemacs-elpa-https t
       dotspacemacs-verify-spacelpa-archives nil
       dotspacemacs-themes '(gruvbox-dark-hard)
       dotspacemacs-colorize-cursor-according-to-state t
       dotspacemacs-mode-line-theme 'spacemacs
       dotspacemacs-scratch-mode 'text-mode
       dotspacemacs-startup-banner 'official
       dotspacemacs-startup-lists '((recents . 5) (projects . 7))))

    (defun dotspacemacs/user-init ()
      ;; Quieten native-comp warnings during async compilation
      (when (boundp 'native-comp-async-report-warnings-errors)
        (setq native-comp-async-report-warnings-errors 'silent)))

    (defun dotspacemacs/user-config ()
      ;; Ensure Nix-provided Forge is loaded (without ELPA install)
      (with-eval-after-load 'magit
        (require 'forge)))
  '';

  # Provide Spacemacs from flake input (tracked in flake.lock)
  home.file.".emacs.d" = {
    source = inputs.spacemacs;
    recursive = true;
  };

  # Remove old XDG init to ensure Spacemacs loads (Emacs 27+ prefers XDG)
  home.activation.removeXDGInit = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    XDG_INIT="${config.home.homeDirectory}/.config/emacs/init.el"
    if [ -L "$XDG_INIT" ] || [ -f "$XDG_INIT" ]; then
      echo "[home.activation] Removing legacy XDG init at $XDG_INIT" >&2
      rm -f "$XDG_INIT"
      rmdir --ignore-fail-on-non-empty "${config.home.homeDirectory}/.config/emacs" 2>/dev/null || true
    fi
  '';

  programs.nh = {
    enable = true;
    clean.enable = true;
    clean.extraArgs = "--keep-since 4d --keep 3";
    flake = "${config.home.homeDirectory}/Code/personal/dotfiles";
  };

  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
  };

  programs.java = {
    enable = true;
    package = pkgs.openjdk21;
  };
}
