{ inputs, lib, ... }:
let
  hubEnvAge = "${inputs.secrets}/server/beszel-hub.env.age";
  agentEnvAge = "${inputs.secrets}/server/beszel-agent.env.age";
in
{
  flake.modules.nixos."services.beszel" =
    {
      config,
      pkgs,
      ...
    }:
    let
      beszelVersion = "0.19.0";
      beszelHubArchive = pkgs.fetchurl {
        url = "https://github.com/henrygd/beszel/releases/download/v${beszelVersion}/beszel_linux_amd64.tar.gz";
        hash = "sha256-Y7INbKMo3AjliBJtouE/i+zmrodd5fJaBY9Iy26hmZg=";
      };
      beszelAgentArchive = pkgs.fetchurl {
        url = "https://github.com/henrygd/beszel/releases/download/v${beszelVersion}/beszel-agent_linux_amd64.tar.gz";
        hash = "sha256-D4WJGykBRrM29cgT0eU16ZLaNe553odukg4ux0ircyw=";
      };
      beszelPackage = pkgs.runCommand "beszel-${beszelVersion}" { } ''
        mkdir -p hub agent "$out/bin"
        ${pkgs.gnutar}/bin/tar -xzf ${beszelHubArchive} -C hub
        ${pkgs.gnutar}/bin/tar -xzf ${beszelAgentArchive} -C agent
        install -m 0755 hub/beszel "$out/bin/beszel-hub"
        install -m 0755 agent/beszel-agent "$out/bin/beszel-agent"
      '';
      hasHubEnv = builtins.pathExists hubEnvAge;
      hasAgentEnv = builtins.pathExists agentEnvAge;
      hubEnvPath = "/run/agenix/beszel-hub-env";
      agentEnvPath = "/run/agenix/beszel-agent-env";
    in
    {
      assertions = [
        {
          assertion = hasHubEnv;
          message = "Beszel requires ${hubEnvAge}.";
        }
        {
          assertion = !(builtins.elem 8090 config.networking.firewall.allowedTCPPorts);
          message = "Beszel must not open TCP port 8090 directly.";
        }
        {
          assertion = !(builtins.elem 45876 config.networking.firewall.allowedTCPPorts);
          message = "Beszel agent must not open TCP port 45876 directly.";
        }
      ];

      age.secrets = {
        "beszel-hub-env" = {
          file = hubEnvAge;
          path = hubEnvPath;
          owner = "root";
          group = "root";
          mode = "0400";
        };
      }
      // lib.optionalAttrs hasAgentEnv {
        "beszel-agent-env" = {
          file = agentEnvAge;
          path = agentEnvPath;
          owner = "root";
          group = "root";
          mode = "0400";
        };
      };

      services.beszel.hub = {
        enable = true;
        package = beszelPackage;
        host = "0.0.0.0";
        port = 8090;
        environment = {
          APP_URL = "http://server.tail7e8d6c.ts.net:8090";
          CHECK_UPDATES = "false";
        };
        environmentFile = hubEnvPath;
      };

      # The agent's key and registration token are generated by the Beszel hub
      # after its first start. Keeping this conditional lets the hub bootstrap
      # safely before those secrets are added to the private secrets input.
      services.beszel.agent = lib.mkIf hasAgentEnv {
        enable = true;
        package = beszelPackage;
        openFirewall = false;
        environment = {
          HUB_URL = "http://127.0.0.1:8090";
          LISTEN = "127.0.0.1:45876";
          SYSTEM_NAME = "server";
          SERVICE_PATTERNS = "docker-*.service,plane.service,ntfy-sh.service";
        };
        environmentFile = agentEnvPath;
      };

      systemd.services.beszel-hub = {
        restartTriggers = [ hubEnvAge ];
        # Nixpkgs 26.05 still invokes the removed `history-sync` command.
        # Beszel 0.19 performs its schema work through `migrate up` only.
        serviceConfig.ExecStartPre = lib.mkForce [ "${beszelPackage}/bin/beszel-hub migrate up" ];
      };

    };
}
